# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

#stages > jobs > steps
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
      - script: echo Building the project...
        displayName: 'Build Step'
      - script: echo Build completed successfully!
        displayName: 'Post Build Step'

      - task: CmdLine@2
        inputs:
          script: |
            echo $(Test)
            echo Hello world


