trigger:
  - main

pool:
  vmImage: ubuntu-latest

#stages > jobs > steps:

stages:
 - stage: "Builds"
   displayName: "Build env"
   jobs:
   - job: "JOB1"
     steps:
       - bash: $(System.DefaultWorkingDirectory)
       - bash: $(Build.SourceDirectory)  


   
