# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage:  "Build Stage"

    jobs:
      - job: "builds"
        displayName: "first job"

        steps:
        - script: echo "First step"
          displayName: First step desc......

        - script: |
            echo "Second step"
            echo "Second step"
          displayName: Second step desc......

      - job: "deploys"
        
        displayName: "second job"
        

        steps:
        - script: echo "second step"
          displayName: First step desc...

        - script: |
            echo "Second step"
            echo "Second step"
          displayName: Second step desc...