trigger:
  - main

pool:
  vmImage: ubuntu-latest

#stages > jobs > steps:

stages:
 - stage: "Builds"
   displayName: "Build env"
   jobs:
   
   - job: 
     displayName: "Job1"
     steps:
     - bash: echo $(System.DefaultWorkingDirectory)
     - bash: echo "Shashi"
   
     - task: CopyFiles@2
       inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: '**/*.*'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

     - script: |
          echo "Listing files in $(Build.ArtifactStagingDirectory)"
          ls -R $(Build.ArtifactStagingDirectory)
       displayName: "List files in Artifact Staging Directory"

     - script: |
         echo "Artifacts"
     - task: PublishBuildArtifacts@1
       inputs:
             PathtoPublish: '$(Build.ArtifactStagingDirectory)'
             ArtifactName: 'drop'
             publishLocation: 'Container'