trigger:
  - main

pool:
  vmImage: ubuntu-latest

#stages > jobs > steps:

stages:
 - stage: "Builds"
   displayName: "Build env"
   jobs:
   
   - job: 
     displayName: "Job1"
     steps:
     - bash: echo $(System.DefaultWorkingDirectory)
     - bash: echo $(Build.SourceDirectory)
   
