trigger:
  - main

pool:
  vmImage: ubuntu-latest

#stages > jobs > steps:

stages:
 - stage: "Builds"
   displayName: "Build env"
   jobs:
   
   - job: 
     displayName: "Job1"
     steps:
     - bash: echo "step1"
       displayName: "step1"
     - script: echo "echo data"
     - script: echo $(System.DefaultWorkingDirectory)
   
   - job: "job2"
     displayName: "Job2"
     steps:
       - script: echo "This is job 2 of build stage"
       - script: echo "Thank you"
       - bash: echo "bash statement"

 - stage: "Devenv"
   displayName: "Devenv"
   dependsOn: "Builds"
   jobs:
   - job: "Devenvjob1"
     displayName: "Job1 of satge 2"
     steps:
       - script: echo "job1"
       - script: echo "job2"
       - bash: echo "Job3"

   - job: "Devjob2"
     displayName: "JOb4Dev"
     steps:
       - script: |
           echo "List1"
           echo "List2"
           echo "list3"
     
 - stage: "QAenv"
   displayName: "QAenv"
   dependsOn: "Builds"
   jobs:
   - job: "QAenvjob1"
     displayName: "Job1 of satge 2"
     steps:
       - script: echo "job1"
       - script: echo "job2"
       - bash: echo "Job3"

   - job: "QAjob2"
     displayName: "JOb4Dev"
     steps:
       - script: |
           echo "List1"
           echo "List2"
           echo "list3"
     
 - stage: "Prodenv"
   displayName: "Prodenv"
   condition: and(succeeded('Devenv'), succeeded('QAenv'))
   dependsOn: 
    - Devenv
    - QAenv
   jobs:
   - job: "Prodenvjob1"
     displayName: "Job1 of satge 2"
     steps:
       - script: echo "job1"
       - script: echo "job2"
       - bash: echo "Job3"

   - job: "Prodjob2"
     displayName: "JOb4Dev"
     steps:
       - script: |
           echo "List1"
           echo "List2"
           echo "list3"

  
     
