trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
 - stage: Build
   displayName: "Build Stage"
   jobs:
    - job: Buildjob
      steps:
       - script: echo "Build script"
         displayName: "script build"
       - script: |
          echo "aaaaa"
          echo "bbbb"
    - job: "DevEnv"
      steps:
       - script: 
          echo "Dev script"

